<?php

namespace Database\Seeders;

use App\Models\Admin;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CustomerSeeder extends Seeder
{
    public function run(): void
    {
        $adminId = Admin::first()->id;
        $now = now();

        $customers = [
            ['code' => 'CUST-0001', 'name' => 'Vikram Mehta',      'company' => 'Mehta Leather Works',           'gst_number' => '33AABCM1234A1ZP', 'email' => 'vikram@mehtaleather.in',       'phone' => '+91 98400 11001', 'billing_address' => '12, Mint Street, Sowcarpet',                  'shipping_address' => '12, Mint Street, Sowcarpet',                  'city' => 'Chennai',    'state' => 'Tamil Nadu',      'pincode' => '600079', 'credit_limit' => 300000],
            ['code' => 'CUST-0002', 'name' => 'Ravi Shankar',      'company' => 'Chennai Apparels Pvt. Ltd.',    'gst_number' => '33AABCC2345B1ZQ', 'email' => 'ravi@chennaiapparels.com',     'phone' => '+91 98400 11002', 'billing_address' => '45, T Nagar Main Road',                      'shipping_address' => '45, T Nagar Main Road',                      'city' => 'Chennai',    'state' => 'Tamil Nadu',      'pincode' => '600017', 'credit_limit' => 500000],
            ['code' => 'CUST-0003', 'name' => 'Anjali Desai',      'company' => 'Desai Fashion House',           'gst_number' => '27AABCD3456C1ZR', 'email' => 'anjali@desaifashion.in',       'phone' => '+91 98200 11003', 'billing_address' => '78, Hill Road, Bandra West',                 'shipping_address' => '78, Hill Road, Bandra West',                 'city' => 'Mumbai',     'state' => 'Maharashtra',     'pincode' => '400050', 'credit_limit' => 400000],
            ['code' => 'CUST-0004', 'name' => 'Sunil Reddy',       'company' => 'Reddy Traders',                 'gst_number' => '36AABCR4567D1ZS', 'email' => 'sunil@reddytraders.com',       'phone' => '+91 98490 11004', 'billing_address' => '23, Abids Circle',                           'shipping_address' => '23, Abids Circle',                           'city' => 'Hyderabad',  'state' => 'Telangana',       'pincode' => '500001', 'credit_limit' => 200000],
            ['code' => 'CUST-0005', 'name' => 'Deepa Krishnan',    'company' => 'KrisStyle Boutique',            'gst_number' => '32AABCK5678E1ZT', 'email' => 'deepa@krisstyle.in',           'phone' => '+91 94470 11005', 'billing_address' => '56, MG Road, Ernakulam',                     'shipping_address' => '56, MG Road, Ernakulam',                     'city' => 'Kochi',      'state' => 'Kerala',          'pincode' => '682011', 'credit_limit' => 150000],
            ['code' => 'CUST-0006', 'name' => 'Arjun Singh',       'company' => 'Delhi Leather Emporium',        'gst_number' => '07AABCD6789F1ZU', 'email' => 'arjun@dleleather.com',         'phone' => '+91 99110 11006', 'billing_address' => '89, Karol Bagh Main Market',                 'shipping_address' => '89, Karol Bagh Main Market',                 'city' => 'New Delhi',  'state' => 'Delhi',           'pincode' => '110005', 'credit_limit' => 350000],
            ['code' => 'CUST-0007', 'name' => 'Neha Gupta',        'company' => 'Gupta Exports',                 'gst_number' => '09AABCG7890G1ZV', 'email' => 'neha@guptaexports.com',        'phone' => '+91 95320 11007', 'billing_address' => '34, Civil Lines',                            'shipping_address' => '34, Civil Lines',                            'city' => 'Lucknow',    'state' => 'Uttar Pradesh',   'pincode' => '226001', 'credit_limit' => 250000],
            ['code' => 'CUST-0008', 'name' => 'Karthik Iyer',      'company' => 'Iyer & Sons Enterprises',       'gst_number' => '29AABCI8901H1ZW', 'email' => 'karthik@iyersons.in',          'phone' => '+91 98450 11008', 'billing_address' => '67, Commercial Street',                      'shipping_address' => '67, Commercial Street',                      'city' => 'Bangalore',  'state' => 'Karnataka',       'pincode' => '560001', 'credit_limit' => 300000],
            ['code' => 'CUST-0009', 'name' => 'Pooja Agarwal',     'company' => 'Agarwal Retail Chain',          'gst_number' => '19AABCA9012I1ZX', 'email' => 'pooja@agarwalretail.in',       'phone' => '+91 98310 11009', 'billing_address' => '12, Park Street',                            'shipping_address' => '12, Park Street',                            'city' => 'Kolkata',    'state' => 'West Bengal',     'pincode' => '700016', 'credit_limit' => 200000],
            ['code' => 'CUST-0010', 'name' => 'Rajesh Patel',      'company' => 'Patel Leathercraft',            'gst_number' => '24AABCP0123J1ZY', 'email' => 'rajesh@patelcraft.com',        'phone' => '+91 98250 11010', 'billing_address' => '90, CG Road, Navrangpura',                   'shipping_address' => '90, CG Road, Navrangpura',                   'city' => 'Ahmedabad',  'state' => 'Gujarat',         'pincode' => '380009', 'credit_limit' => 250000],
            ['code' => 'CUST-0011', 'name' => 'Shalini Joshi',     'company' => 'Joshi Garments',                'gst_number' => '20AABCJ1234K1ZZ', 'email' => 'shalini@joshigarments.in',     'phone' => '+91 98350 11011', 'billing_address' => '45, Ranchi Road',                            'shipping_address' => '45, Ranchi Road',                            'city' => 'Jamshedpur', 'state' => 'Jharkhand',       'pincode' => '831001', 'credit_limit' => 100000],
            ['code' => 'CUST-0012', 'name' => 'Amitabh Roy',       'company' => 'Royal Fashion Ltd.',            'gst_number' => '33AABCR2345L1ZA', 'email' => 'amitabh@royalfashion.in',      'phone' => '+91 98400 11012', 'billing_address' => '23, Anna Salai',                             'shipping_address' => '23, Anna Salai',                             'city' => 'Chennai',    'state' => 'Tamil Nadu',      'pincode' => '600002', 'credit_limit' => 450000],
            ['code' => 'CUST-0013', 'name' => 'Meena Kumari',      'company' => 'Kumari Collections',            'gst_number' => '29AABCK3456M1ZB', 'email' => 'meena@kumaricollections.in',   'phone' => '+91 98860 11013', 'billing_address' => '78, MG Road, Shivajinagar',                  'shipping_address' => '78, MG Road, Shivajinagar',                  'city' => 'Bangalore',  'state' => 'Karnataka',       'pincode' => '560051', 'credit_limit' => 180000],
            ['code' => 'CUST-0014', 'name' => 'Faisal Khan',       'company' => 'Khan Leather Goods',            'gst_number' => '23AABCK4567N1ZC', 'email' => 'faisal@khanleather.com',       'phone' => '+91 98270 11014', 'billing_address' => '56, Sarafa Bazar',                           'shipping_address' => '56, Sarafa Bazar',                           'city' => 'Indore',     'state' => 'Madhya Pradesh',  'pincode' => '452001', 'credit_limit' => 120000],
            ['code' => 'CUST-0015', 'name' => 'Lavanya Menon',     'company' => 'Menon Lifestyle Pvt. Ltd.',     'gst_number' => '32AABCM5678O1ZD', 'email' => 'lavanya@menonlifestyle.in',    'phone' => '+91 94950 11015', 'billing_address' => '34, Marine Drive',                           'shipping_address' => '34, Marine Drive',                           'city' => 'Kochi',      'state' => 'Kerala',          'pincode' => '682031', 'credit_limit' => 200000],
            ['code' => 'CUST-0016', 'name' => 'Sanjay Tiwari',     'company' => 'Tiwari Brothers',               'gst_number' => '09AABCT6789P1ZE', 'email' => 'sanjay@tiwaribrothers.in',     'phone' => '+91 94150 11016', 'billing_address' => '89, Hazratganj',                             'shipping_address' => '89, Hazratganj',                             'city' => 'Lucknow',    'state' => 'Uttar Pradesh',   'pincode' => '226001', 'credit_limit' => 150000],
            ['code' => 'CUST-0017', 'name' => 'Prashant Nair',     'company' => 'Nair Apparels',                 'gst_number' => '33AABCN7890Q1ZF', 'email' => 'prashant@nairapparels.in',     'phone' => '+91 98400 11017', 'billing_address' => '12, Cathedral Road',                         'shipping_address' => '12, Cathedral Road',                         'city' => 'Chennai',    'state' => 'Tamil Nadu',      'pincode' => '600086', 'credit_limit' => 350000],
            ['code' => 'CUST-0018', 'name' => 'Divya Bhatt',       'company' => 'Bhatt Handicrafts',             'gst_number' => '08AABCB8901R1ZG', 'email' => 'divya@bhattcraft.in',          'phone' => '+91 94140 11018', 'billing_address' => '45, Johari Bazar',                           'shipping_address' => '45, Johari Bazar',                           'city' => 'Jaipur',     'state' => 'Rajasthan',       'pincode' => '302003', 'credit_limit' => 180000],
            ['code' => 'CUST-0019', 'name' => 'Gopal Shetty',      'company' => 'Shetty Enterprises',            'gst_number' => '27AABCS9012S1ZH', 'email' => 'gopal@shettyent.com',          'phone' => '+91 98200 11019', 'billing_address' => '67, Linking Road, Khar',                     'shipping_address' => '67, Linking Road, Khar',                     'city' => 'Mumbai',     'state' => 'Maharashtra',     'pincode' => '400052', 'credit_limit' => 280000],
            ['code' => 'CUST-0020', 'name' => 'Rekha Verma',       'company' => 'Verma Exports Pvt. Ltd.',       'gst_number' => '06AABCV0123T1ZI', 'email' => 'rekha@vermaexports.in',        'phone' => '+91 98720 11020', 'billing_address' => '23, Sector 17, Chandigarh',                  'shipping_address' => '23, Sector 17, Chandigarh',                  'city' => 'Chandigarh', 'state' => 'Chandigarh',      'pincode' => '160017', 'credit_limit' => 220000],
            ['code' => 'CUST-0021', 'name' => 'Mohan Das',         'company' => 'Das Leather & Co.',             'gst_number' => '33AABCD1234U1ZJ', 'email' => 'mohan@dasleather.in',          'phone' => '+91 98400 11021', 'billing_address' => '90, Pondy Bazaar, T Nagar',                  'shipping_address' => '90, Pondy Bazaar, T Nagar',                  'city' => 'Chennai',    'state' => 'Tamil Nadu',      'pincode' => '600017', 'credit_limit' => 400000],
            ['code' => 'CUST-0022', 'name' => 'Sunita Rao',        'company' => 'Rao Fashion Studio',            'gst_number' => '29AABCR2345V1ZK', 'email' => 'sunita@raofashion.in',         'phone' => '+91 98450 11022', 'billing_address' => '34, Brigade Road',                           'shipping_address' => '34, Brigade Road',                           'city' => 'Bangalore',  'state' => 'Karnataka',       'pincode' => '560025', 'credit_limit' => 150000],
            ['code' => 'CUST-0023', 'name' => 'Arun Pillai',       'company' => 'Pillai Trading Co.',            'gst_number' => '32AABCP3456W1ZL', 'email' => 'arun@pillaitrading.in',        'phone' => '+91 94470 11023', 'billing_address' => '56, Broadway, Ernakulam',                    'shipping_address' => '56, Broadway, Ernakulam',                    'city' => 'Kochi',      'state' => 'Kerala',          'pincode' => '682011', 'credit_limit' => 130000],
            ['code' => 'CUST-0024', 'name' => 'Nandini Hegde',     'company' => 'Hegde Retail',                  'gst_number' => '29AABCH4567X1ZM', 'email' => 'nandini@hegderetail.in',       'phone' => '+91 98860 11024', 'billing_address' => '78, Jayanagar 4th Block',                    'shipping_address' => '78, Jayanagar 4th Block',                    'city' => 'Bangalore',  'state' => 'Karnataka',       'pincode' => '560041', 'credit_limit' => 170000],
            ['code' => 'CUST-0025', 'name' => 'Harish Kapoor',     'company' => 'Kapoor & Associates',           'gst_number' => '07AABCK5678Y1ZN', 'email' => 'harish@kapoorassociates.in',   'phone' => '+91 99110 11025', 'billing_address' => '12, Connaught Place',                        'shipping_address' => '12, Connaught Place',                        'city' => 'New Delhi',  'state' => 'Delhi',           'pincode' => '110001', 'credit_limit' => 500000],
        ];

        $rows = [];
        foreach ($customers as $c) {
            $c['country'] = 'India';
            $c['notes'] = null;
            $c['status'] = 'active';
            $c['created_by'] = $adminId;
            $c['updated_by'] = null;
            $c['deleted_by'] = null;
            $c['created_at'] = $now;
            $c['updated_at'] = $now;
            $c['deleted_at'] = null;
            $rows[] = $c;
        }

        DB::table('customers')->insert($rows);
    }
}
